# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Native Test

on:
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set timezone
        run: sudo timedatectl set-timezone "America/Denver"

      - name: Set BUILD_DATE
        run: |
          BUILD_DATE=$(date +%Y-%m-%d)
          echo "BUILD_DATE=$BUILD_DATE" >> "$GITHUB_ENV"

      - name: Set up Go
        uses: actions/setup-go@7b8cf10d4e4a01d4992d18a89f4d7dc5a3e6d6f4 # v4.3.0
        with:
          go-version: '1.23'
  
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1


      - name: Test
        run: go test -v -ldflags "-X version.gitSha=$GIT_SHA -X version.buildDate=$BUILD_DATE" ./...